[package]
name = "linc"
version = "0.1.0"
edition = "2021"

[dependencies]
gurtlib = "0.1"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
